package PageObjects;

import NopCommerce.Utils;
import org.openqa.selenium.By;
import org.testng.asserts.SoftAssert;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;

/**
 * Created by Welcome on 29/07/2017.
 */
public class ComputersPage extends Utils {

    private By _computer = By.xpath("//body/div[6]/div[2]/ul/li/a");
    private By _desktop = By.xpath("//a[contains (@href, \"/desktops\")]");
    private By _buildYourOwn = By.linkText("Build your own computer");
    private By _emailFriend = By.xpath("//input[contains (@class, \"button-2 email-a-friend-button\")and contains(@value, \"Email a friend\")]");
    private By _friendEmail = By.id("FriendEmail");
    private By _yourEmail = By.id("YourEmailAddress");
    private By _personalMessage = By.id("PersonalMessage");
    private By _sendEmailButton = By.xpath("//input[contains (@class, \"button-1 send-email-a-friend-button\")and contains(@name, \"send-email\")]");
    private By _pageTitle = By.className("page-title");
    private By _productName = By.className("product-name");

    public void clickComputer() {

        SoftAssert softAssertObj = new SoftAssert();
        String actualString;

        //click on computer
        myClick(_computer);

        //Soft assert
        actualString = getText(_pageTitle);
        softAssertObj.assertEquals(actualString, "Computers", "Computers page is not loaded");

        //click desktop
        myClick(_desktop);

        //Soft assert
        actualString = getText(_pageTitle);
        softAssertObj.assertEquals(actualString, "Desktops", "Desktops page is not loaded");

        //click first product "build your own"
        myClick(_buildYourOwn);

        //Soft assert
        actualString = getText(_productName);
        softAssertObj.assertEquals(actualString, "Build your own computer", "Build your own computer product page is not loaded");

        //click on Email a Friend
        myClick(_emailFriend);

        //Soft assert
        actualString = getText(_pageTitle);
        softAssertObj.assertEquals(actualString, "Email a friend", "Email a friend page is not loaded");

        //click on frind email field and insert email ID
        myEnterText(_friendEmail, "bhagirath.test@yaho.com");

        //click on your email. Clear text and enter email ID generated by randomnumber
        clearText(_yourEmail);
        randomNumber(_yourEmail, "bhagirath");

        //click on perosnal message and write message to friend
        myEnterText(_personalMessage, "Hi Bhagirath. Check this out. You should really buy this desktop. It is amazing.");

        //click on send email button
        myClick(_sendEmailButton);

        softAssertObj.assertAll();
    }
}
